# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html

version = 0.1

[default.global.parameters]
stack_name = "fulfillment-api"
 
[default.deploy.parameters]
region = "us-west-2"
s3_bucket = "fulfillment-api-source"
s3_prefix = "default"
capabilities = "CAPABILITY_IAM"
use_container = true
confirm_changeset = false
fail_on_empty_changeset = false
tags = "project=\"fulfillment-api\" stage=\"production\""

[default.build.parameters]
cached = true