# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html

version = 0.1

[default.global.parameters]
stack_name = "fulfillment-api"
 
[default.deploy.parameters]
region = "us-west-2"
resolve_s3 = true
s3_prefix = "default"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
tags = "project=\"fulfillment-api\" stage=\"production\""

[default.build.parameters]
use_container = true