on:
  push:
    branches:
      - master
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - name: Run Rubocop
      run: |
        gem install rubocop
        rubocop --parallel
  rspec:
    needs: rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - uses: rrainn/dynamodb-action@v2.0.0
        with:
          port: 8001
          cors: '*'
      - name: Run tests
        run: |
          bundle install
          bundle exec rspec
  build-deploy:
    needs: rspec
    runs-on: ubuntu-latest
    permissions: # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#adding-permissions-settings
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-west-2
      - uses: aws-actions/setup-sam@v1
      - run: sam build
      # Run Unit tests- Specify unit tests here
      - run: sam deploy