on:
  push:
    branches:
      - master
jobs:
  # test:
  #   uses: machineboy2045/github-actions-with-aws-sam/.github/workflows/test.yml@master
  build-deploy:
    # needs: test
    runs-on: ubuntu-latest
    permissions: # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#adding-permissions-settings
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-2
      # sam build 
      - uses: aws-actions/setup-sam@v1
      - run: sam build --use-container

# Run Unit tests- Specify unit tests here 

# sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-hello-world --s3-bucket sam-hello-world-fulfillment-api --capabilities CAPABILITY_IAM --region us-east-2